### ISSUE TITLE
Rider Application: Fix Rider Application Form Fields and Rider Application Show Page

### ISSUE THREAD

**Issue by calee14** [ucsb-cs156-w24/proj-gauchoride-w24-7pm-3#22]
## Fields on RiderApplicationForm
* `id` (only if the rider has already applied; this should be labelled as `applicant id` on the form, but is just `id` internally)
* `status` this will be pre-populated with the status of the application: (pending for newly created applications) and will not be editable.  See status values below.
* `email` this will be pre-populated from the current user and will not be editable, but will appear
* `perm_number`  This field will be editable  and will accept the perm number.  Perm numbers are 7 characters, and are now alphanumeric (not just numeric).  
* `date applied` this will be pre-populated with the date the application was first created, and is not editable
* `date updated` this will be pre-populated with the date the application was last updated.
* `date cancelled`   this will be pre-populated with the date the application was cancelled (if and only if it was cancelled)
* `description` This will be an editable text field that should be, initially, the full width of the container and at least 6 lines of text high, and should be expandable.  It will be labelled with "Please describe the mobility limitations that cause you to need to use the Gauchoride service."
* `notes` This will be a text field that is not editable by the applicant, but will contain information entered by the admin that acts on the application.  This field is for communicating information back to the applicant about the status of their application.

# Task
- [x] The Rider Application Form had two fields: Application Id and Applicant Id. This implementation was wrong and should only have one field for ID which is the rider application ID. This ID can be found in the Rider Application Entities file. 
- [x] The email field the in the form should be auto populated with the current user's email. This was not the case prior.
- [x] Must fix the date update, applied, and cancelled fields to be disabled for all users. Cancelled date field will only show if the application was cancelled. 
- [x] Notes can only be edited by an admin user. Notes should only be displayed if there are notes made by the admin. 
- [x] Current tests do not test form well (at all). Add some more tests.
- [X] Make a show page for the form where none of the fields are editable.
