### ISSUE TITLE
Admin Rider Application Review Form

### ISSUE THREAD

**Issue by calee14** [ucsb-cs156-w24/proj-gauchoride-w24-7pm-3#48]
## 
- [ ] For pending applications, the admin has buttons to "Approve", "Deny", "Save".   All three save any edits to the response field.  In addition, "Accept" or "Decline" will change the status of the application to "Accepted" or "Declined".  There is also a "Return without Saving" button that returns to the `/admin/applications/riders` without saving any changes to the form.
- [ ] For applications in the status "accepted", there is a button on the `/admin/applications/riders/review/:id`  page called "Set Status to Expired", and one called  "Return without Saving".   In this case the notes field is editable.  The "Set Status to Expired" button will update the status to expired and save the changes.  The "Return without Saving" returns to the `/admin/applications/riders` discarding any changes to the form.

## Tasks
- [ ] Build a form with stories and tests that fulfill the requirements above.
